export const characters: {
    [key: string]: {
        code: number,
        label: string,
        string: string,
        sound: string,
    }
} = {
    'space': { 'code': 32, 'label': '!', 'string': '!', 'sound': 'すぺーす' },
    '!': { 'code': 33, 'label': '!', 'string': '!', 'sound': 'びっくりまーく' },
    '"': { 'code': 34, 'label': '"', 'string': '"', 'sound': 'だぶるくぉーと' },
    '#': { 'code': 35, 'label': '#', 'string': '#', 'sound': 'しゃーぷ' },
    '$': { 'code': 36, 'label': '%', 'string': '%', 'sound': 'どる' },
    '%': { 'code': 37, 'label': '%', 'string': '%', 'sound': 'ぱーせんと' },
    '&': { 'code': 38, 'label': '&', 'string': '&', 'sound': 'あんど' },
    "'": { 'code': 39, 'label': "'", 'string': "'", 'sound': 'くぉーと' },
    '(': { 'code': 40, 'label': '(', 'string': '(', 'sound': '小かっこ' },
    ')': { 'code': 41, 'label': ')', 'string': ')', 'sound': '小かっこ（とじる）' },
    '{': { 'code': 40, 'label': '{', 'string': '{', 'sound': '中カッコ' },
    '}': { 'code': 41, 'label': '}', 'string': '}', 'sound': '中カッコ（とじる）' },
    '*': { 'code': 42, 'label': '*', 'string': '*', 'sound': 'あすたりすく' },
    '+': { 'code': 43, 'label': '+', 'string': '+', 'sound': 'ぷらす' },
    '-': { 'code': 45, 'label': '-', 'string': '-', 'sound': 'まいなす' },
    '=': { 'code': 61, 'label': '-', 'string': '-', 'sound': 'いこーる' },
    '^': { 'code': 94, 'label': '^', 'string': '^', 'sound': 'きゃれっと' },
    '`': { 'code': 94, 'label': '`', 'string': '`', 'sound': 'ばっくくぉーと' },
    '~': { 'code': 126, 'label': '^', 'string': '^', 'sound': 'ちるだ' },
    '¥': { 'code': 165, 'label': '¥', 'string': '¥', 'sound': 'えんまーく' },
    '|': { 'code': 124, 'label': '^', 'string': '^', 'sound': 'ぱいぷ' },
    '@': { 'code': 64, 'label': '@', 'string': '@', 'sound': 'あっとまーく' },
    '<': { 'code': 60, 'label': '<', 'string': '<', 'sound': '小なり' },
    '>': { 'code': 62, 'label': '>', 'string': '>', 'sound': '大なり' },
    '[': { 'code': 91, 'label': '[', 'string': '[', 'sound': 'ぶらけっと（ひだり）' },
    ']': { 'code': 93, 'label': ']', 'string': ']', 'sound': 'ぶらけっと（みぎ）' },
    ':': { 'code': 58, 'label': ':', 'string': ':', 'sound': 'ころん' },
    ';': { 'code': 59, 'label': ';', 'string': ';', 'sound': 'せみころん' },
    ',': { 'code': 44, 'label': ',', 'string': ',', 'sound': 'かんま' },
    '.': { 'code': 46, 'label': '.', 'string': '.', 'sound': 'ぴりおど' },
    '/': { 'code': 47, 'label': '_', 'string': '/', 'sound': 'すらっしゅ' },
    '?': { 'code': 63, 'label': '_', 'string': '/', 'sound': 'くえすちょん' },
    '_': { 'code': 95, 'label': '_', 'string': '_', 'sound': 'あんだーすこあ' },
    '1': { 'code': 49, 'label': '1', 'string': '1', 'sound': 'いち' },
    '2': { 'code': 51, 'label': '2', 'string': '2', 'sound': 'に' },
    '3': { 'code': 52, 'label': '3', 'string': '3', 'sound': 'さん' },
    '4': { 'code': 53, 'label': '4', 'string': '4', 'sound': 'よん' },
    '5': { 'code': 54, 'label': '5', 'string': '5', 'sound': 'ご' },
    '6': { 'code': 55, 'label': '6', 'string': '6', 'sound': 'ろく' },
    '7': { 'code': 56, 'label': '7', 'string': '7', 'sound': 'しち' },
    '8': { 'code': 57, 'label': '8', 'string': '8', 'sound': 'はち' },
    '9': { 'code': 58, 'label': '9', 'string': '9', 'sound': 'きゅう' },
    '0': { 'code': 48, 'label': '0', 'string': '0', 'sound': 'ぜろ' },
    'a': { 'code': 97, 'label': 'A', 'string': 'a', 'sound': 'えい' },
    'b': { 'code': 98, 'label': 'B', 'string': 'b', 'sound': 'びー' },
    'c': { 'code': 99, 'label': 'C', 'string': 'c', 'sound': 'すぃー' },
    'd': { 'code': 100, 'label': 'D', 'string': 'd', 'sound': 'でぃー' },
    'e': { 'code': 101, 'label': 'E', 'string': 'e', 'sound': 'いー' },
    'f': { 'code': 102, 'label': 'F', 'string': 'f', 'sound': 'えふ' },
    'g': { 'code': 103, 'label': 'G', 'string': 'g', 'sound': 'じー' },
    'h': { 'code': 104, 'label': 'H', 'string': 'h', 'sound': 'えいち' },
    'i': { 'code': 105, 'label': 'I', 'string': 'i', 'sound': 'あい' },
    'j': { 'code': 106, 'label': 'J', 'string': 'j', 'sound': 'じぇい' },
    'k': { 'code': 107, 'label': 'K', 'string': 'k', 'sound': 'けい' },
    'l': { 'code': 108, 'label': 'L', 'string': 'l', 'sound': 'える' },
    'm': { 'code': 109, 'label': 'M', 'string': 'm', 'sound': 'えむ' },
    'n': { 'code': 110, 'label': 'N', 'string': 'n', 'sound': 'えぬ' },
    'o': { 'code': 111, 'label': 'O', 'string': 'o', 'sound': 'おぅ' },
    'p': { 'code': 112, 'label': 'P', 'string': 'p', 'sound': 'ぴー' },
    'q': { 'code': 113, 'label': 'Q', 'string': 'q', 'sound': 'きゅー' },
    'r': { 'code': 114, 'label': 'R', 'string': 'r', 'sound': 'あーる' },
    's': { 'code': 115, 'label': 'S', 'string': 's', 'sound': 'えす' },
    't': { 'code': 116, 'label': 'T', 'string': 't', 'sound': 'てぃー' },
    'u': { 'code': 117, 'label': 'U', 'string': 'u', 'sound': 'ゆー' },
    'v': { 'code': 118, 'label': 'V', 'string': 'v', 'sound': 'ぶい' },
    'w': { 'code': 119, 'label': 'W', 'string': 'w', 'sound': 'だぶりゅー' },
    'x': { 'code': 120, 'label': 'X', 'string': 'x', 'sound': 'えっくす' },
    'y': { 'code': 121, 'label': 'Y', 'string': 'y', 'sound': 'わい' },
    'z': { 'code': 122, 'label': 'Z', 'string': 'z', 'sound': 'ずぃー' },
    'A': { 'code': 65, 'label': 'a', 'string': 'A', 'sound': 'えい' },
    'B': { 'code': 66, 'label': 'b', 'string': 'B', 'sound': 'びー' },
    'C': { 'code': 67, 'label': 'c', 'string': 'C', 'sound': 'すぃー' },
    'D': { 'code': 68, 'label': 'd', 'string': 'D', 'sound': 'でぃー' },
    'E': { 'code': 69, 'label': 'e', 'string': 'E', 'sound': 'いー' },
    'F': { 'code': 70, 'label': 'f', 'string': 'F', 'sound': 'えふ' },
    'G': { 'code': 71, 'label': 'g', 'string': 'G', 'sound': 'じー' },
    'H': { 'code': 72, 'label': 'h', 'string': 'H', 'sound': 'えいち' },
    'I': { 'code': 73, 'label': 'i', 'string': 'I', 'sound': 'あい' },
    'J': { 'code': 74, 'label': 'j', 'string': 'J', 'sound': 'じぇい' },
    'K': { 'code': 75, 'label': 'k', 'string': 'K', 'sound': 'けい' },
    'L': { 'code': 76, 'label': 'l', 'string': 'L', 'sound': 'える' },
    'M': { 'code': 77, 'label': 'm', 'string': 'M', 'sound': 'えむ' },
    'N': { 'code': 78, 'label': 'n', 'string': 'N', 'sound': 'えぬ' },
    'O': { 'code': 79, 'label': 'o', 'string': 'O', 'sound': 'おー' },
    'P': { 'code': 80, 'label': 'p', 'string': 'P', 'sound': 'ぴー' },
    'Q': { 'code': 81, 'label': 'q', 'string': 'Q', 'sound': 'きゅー' },
    'R': { 'code': 82, 'label': 'r', 'string': 'R', 'sound': 'あーる' },
    'S': { 'code': 83, 'label': 's', 'string': 'S', 'sound': 'えす' },
    'T': { 'code': 84, 'label': 't', 'string': 'T', 'sound': 'てぃー' },
    'U': { 'code': 85, 'label': 'u', 'string': 'U', 'sound': 'ゆー' },
    'V': { 'code': 86, 'label': 'v', 'string': 'V', 'sound': 'ぶい' },
    'W': { 'code': 87, 'label': 'w', 'string': 'W', 'sound': 'だぶりゅー' },
    'X': { 'code': 88, 'label': 'x', 'string': 'X', 'sound': 'えっくす' },
    'Y': { 'code': 89, 'label': 'y', 'string': 'Y', 'sound': 'わい' },
    'Z': { 'code': 90, 'label': 'z', 'string': 'Z', 'sound': 'ずぃー' },
};

export const defaultKeys: string[][] = [
    ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '^', '¥'],
    ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '@', '['],
    ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ';', ':', ']'],
    ['Z', 'X', 'C', 'V', 'B', 'N', 'M', ',', '.', '/', '_'],
];

export const shiftKeys: string[][] = [
    ['!', '"', '#', '$', '%', '&', "'", '(', ')', '', '=', '~', '|'],
    ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '`', '{'],
    ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', '+', '*', '}'],
    ['Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', ''],
];

export const kana50: {
    [key: string]: string[]
} = {
    'a': ['あ', 'い', 'う', 'え', 'お'],
    'ka': ['か', 'き', 'く', 'け', 'こ'],
    'sa': ['さ', 'し', 'す', 'せ', 'そ'],
    'ta': ['た', 'ち', 'つ', 'て', 'と'],
    'na': ['な', 'に', 'ぬ', 'ね', 'の'],
    'ha': ['は', 'ひ', 'ふ', 'へ', 'ほ'],
    'ma': ['ま', 'み', 'む', 'め', 'も'],
    'ya': ['や', 'ゆ', 'よ'],
    'ra': ['ら', 'り', 'る', 'れ', 'ろ'],
    'wa': ['わ', 'を', 'ん'],
    'ga': ['が', 'ぎ', 'ぐ', 'げ', 'ご'],
    'za': ['ざ', 'じ', 'ず', 'ぜ', 'ぞ'],
    'da': ['だ', 'ぢ', 'づ', 'で', 'ど'],
    'ba': ['ば', 'び', 'ぶ', 'べ', 'ぼ'],
    'pa': ['ぱ', 'ぴ', 'ぷ', 'ぺ', 'ぽ'],
    'gya': ['ぎゃ', 'ぎゅ', 'ぎょ'],
}

export const romaji50: {
    [key: string]: string[]
} = {
    'a': ['a', 'i', 'u', 'e', 'o'],
    'ka': ['ka', 'ki', 'ku', 'ke', 'ko'],
    'sa': ['sa', 'si', 'su', 'se', 'so'],
    'ta': ['ta', 'ti', 'tu', 'te', 'to'],
    'na': ['na', 'ni', 'nu', 'ne', 'no'],
    'ha': ['ha', 'hi', 'fu', 'he', 'ho'],
    'ma': ['ma', 'mi', 'mu', 'me', 'mo'],
    'ya': ['ya', 'yu', 'yo'],
    'ra': ['ra', 'ri', 'ru', 're', 'ro'],
    'wa': ['wa', 'wo', 'nn'],
    'ga': ['ga', 'gi', 'gu', 'ge', 'go'],
    'za': ['za', 'ji', 'zu', 'ze', 'zo'],
    'da': ['da', 'ji', 'du', 'de', 'do'],
    'ba': ['ba', 'bi', 'bu', 'be', 'bo'],
    'pa': ['pa', 'pi', 'pu', 'pe', 'po'],
    'gya': ['gya', 'gyu', 'gyo'],
}